config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
	resources :pins
	
	root "pins#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "400x400>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
		before_action :find_pin, only: [:show, :edit, :update, :destroy]


	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end

  def new
 		@pin = current_user.pins.build
  end

  def create
 	  @pin = current_user.pins.build(pin_params)
 	  if @pin.save
 	 		redirect_to @pin, notice: "Successfully created new Pin"
 	  else
 	  	render 'new'
 	  end
  end


  def edit
  end

  def update
  	if @pin.update(pin_params)
  		redirect_to @pin, notice: "Pin was Successfully updated !"
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@pin.destroy
  	redirect_to root_path
  end


	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterestdemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Pinterest like</a>
       
        <% if user_signed_in? %>
        
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "New Pin", new_pin_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Account", edit_user_registration_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
           </ul>

        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>


      
    <div class="container">
    	<% flash.each do |name, msg| %>
    		<%= content_tag :div, msg, class: "alert alert-info"%>
    	<% end %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
      <h2></h2>
      <%= pluralize(@pin.errors.count, 'error') %>
      prevented this Pin from saving
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :image, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :title, input_html: {class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: {class: 'form-control'} %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pins/edit.html.erb
<h1>Edit Pin</h1>

<%=render 'form'%>

<%= link_to "Cancel", pin_path %>

app/views/pins/index.html.erb
<div class="container">
	<% @pins.each do |pin|  %>
	<%= link_to (image_tag pin.image.url(:medium)), pin %>
		<h2><%= link_to pin.title,pin %></h2>
	<%end%>
</div>

app/views/pins/new.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-sm-8 col-md-6">
			<h1>New Form</h1>
			<%= render 'form' %>
			<%= link_to "Back", root_path%>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div>
			<%= image_tag @pin.image.url(:medium) %>
		</div>
	</div>
	<div class="row justify-content-center">
		<div>
			<h1><%= @pin.title %></h1>
			<p><%= @pin.description %></p>

			<p><%= @pin.user.email %></p>
		</div>
	</div>

	<div class="row justify-content-center">
		<%= link_to "Back", root_path %>
		<%= link_to "Edit", edit_pin_path %>
		<%= link_to "Delete", pin_path, method: :delete, data:{ confirm: "Are you sure?"} %>
	</div>
</div>